### ISSUE TITLE
quesetions about filtered SLP dataset

### ISSUE THREAD

**Issue by thraster** [RCHI-Lab/BodyMAP#2]
Hello Abhishek

You have done a great job! Congraduations! 

I have noticed in your code that the slp pressure data is from **SLP_filtered**

> self.pressure_data_dir = os.path.join(data_path, 'SLP_filtered', 'danaLab')

I was wondering what kind of filtering you have done? is that going to be avaliable?

Thank you very much!

-chester

**Comment by Tandon-A** [comment]
Hi @thraster , 

Apologies for the delay. 

Thanks for catching this. As the comment on [that line](https://github.com/RCHI-Lab/BodyMAP/blob/main/PMM/SLPDataset.py#L15) mentions, the folder name had to be changed to SLP. I think I missed it. 

We have prepared the datasets as per instructions in [BodyPressure repository](https://github.com/Healthcare-Robotics/BodyPressure), and haven't done any filtering on top of that. 

Best, 
Abhishek
