### ISSUE TITLE
Where is the link

### ISSUE THREAD

**Issue by Michaelapps-Xie** [RCHI-Lab/BodyMAP#3]
There is no link and I cant find the GT_BP_DATA and the parsed
Download the 3D pressure maps for the two datasets and put in BodyPressure/data_BP. ([Link](Public drive link: TODO))
Download the parsed data (part segmented faces indexes, v2vP 1EA and v2vP 2EA indexes) and put in BodyPressure/data_BP. ([Link](Public drive link: TODO))

**Comment by Tandon-A** [comment]
Hi @Michaelapps-Xie , 

We are in the process of releasing the data in the coming week or two. Please watch the repository. 

Thank you for waiting patiently.

**Comment by Tandon-A** [comment]
Hi @Michaelapps-Xie , 

The links have been updated in Readme file. Thank you for waiting patiently.
