### ISSUE TITLE
Encountered Issues with SLP_SMPL_fits Data and Missing Keys in SKPDataset.py During Model Training

### ISSUE THREAD

**Issue by Michaelapps-Xie** [RCHI-Lab/BodyMAP#4]
![1](https://github.com/user-attachments/assets/0b63e39b-61ec-4129-8ae8-072eab789bd3)
![2](https://github.com/user-attachments/assets/c01ae83e-e8f3-4a55-894d-f29be7eee3b5)
![3](https://github.com/user-attachments/assets/42cc7a13-919e-47f8-a5f7-cf508f97d192)
First of all, thank you very much for updating the data download link. However, when I ran your code, I encountered a few issues. In SKPDataset.py at line 83, the code is trying to find .pkl files in the SLP_SMPL_fits directory, but the files I downloaded start with the letter "s"，not the proc. Additionally, at line 92 in the same file (I may have disrupted the original structure while debugging, so you can refer to the screenshot I provided), I couldn't find pose_data['O_T_slp'], pose_data['cam_T_Bo'], and pose_data['Bo_T_Br']. Similarly, at line 95, gt_markers = np.array(pose_data['markers_xyz_m']), I couldn't find pose_data['markers_xyz_m']. Ignoring these, the SLP dataset works for validation and can generate output images correctly. However, when training the model, errors occur, as you can see in the screenshot named 3.png. I am currently trying to test this model on another dataset, but encountered the above issues during training. I hope you can provide a solution. If possible, it would be great if you could provide the trained model weights and the exp.json file generated during training. I appreciate you taking the time to help, and I sincerely thank you again.

**Comment by Tandon-A** [comment]
Hi @Michaelapps-Xie , 

Thank you for bringing this to my attention. 
I have updated the path in readme for SLP_SMPL_fits. You can download the SLP_SMPL_fits data from [Link](https://drive.google.com/file/d/1LiE4gjszpMsrApHuXoE5DMlMFMphpEoM/view?usp=sharing). These updated files include the files: 'O_T_slp', 'cam_T_Bo', 'Bo_T_Br', 'markers_xyz_m' for each participant.

**Comment by Tandon-A** [comment]
> If possible, it would be great if you could provide the trained model weights and the exp.json file generated during training.

You can download the trained models, details are provided in [Readme](https://github.com/RCHI-Lab/BodyMAP?tab=readme-ov-file#trained-models).

**Comment by Michaelapps-Xie** [comment]
![1](https://github.com/user-attachments/assets/c56c74f9-c4aa-4a58-ba3d-01515c44b5a3)
Thank you very much for providing the weights file and the SLP_SMPL_fits file. When running the following command:
metrics.py --files_dir FULL_PATH_OF_SAVED_RESULTS_DIR --save_path FULL_PATH_TO_SAVE_METRICS
I encountered an import error in the script scripts/metrics.py related to the line:
from mesh_mesh_intersection import MeshMeshIntersection
Could you please let me know where I can download and install this package?
